  name: Checkov Scan

  on:
    push:
      branches:
        - dev # Trigger when code is pushed to the dev branch

  permissions:
    security-events: write

  jobs:
    checkov-scan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Install Checkov
          run: |
            python -m pip install --upgrade pip
            pip install checkov

        - name: Run Checkov Scan
          run: |
            checkov --directory . --output-file checkov-results.json --output json --download-external-modules true || true

        - name: Download sarif-cli
          run: |
            curl -L -o sarif-cli https://github.com/microsoft/sarif-cli/releases/latest/download/sarif-cli-linux-x64
            chmod +x sarif-cli

        - name: Convert JSON to SARIF
          run: |
            ./sarif-cli convert checkov-results.json --output checkov-results.sarif

        - name: Upload results
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: checkov-results.sarif