name: Terraform Plan Workflow

on:
  pull_request:
    branches:
      - master # Trigger on pull requests targeting the master branch

env:
  CONFIG_DIRECTORY: "."
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write 

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      # Step 3: Configure AWS credentials
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      #    # Step 6: Upload tfplan as Artifact
      # - name: Upload Plan Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: tfplan
      #     path: ${{ env.CONFIG_DIRECTORY }}/tfplan