name: Terraform Workflow

on:
  pull_request:
    branches:
      - master # Trigger when a PR is merged into the master branch

env:
  TF_CLOUD_ORGANIZATION: "nt548-akt"
  TF_WORKSPACE: "notebook-infrastructure" 
  CONFIG_DIRECTORY: "."

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write 

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      # Step 3: Configure Terraform Backend
      - name: Terraform Init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      # Step 4: Terraform Plan
      - name: Terraform Plan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform plan -out=tfplan
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      # Step 5: Terraform Apply
      - name: Terraform Apply
        if: github.event.pull_request.merged == true # Only run if the PR was merged
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.CONFIG_DIRECTORY }}