name: Terraform Apply Workflow

on:
  workflow_run:
    workflows:
      - "Terraform Plan Workflow" # Triggered after the Plan workflow completes
    types:
      - completed # Trigger only on workflow completion

env:
  CONFIG_DIRECTORY: "."
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download tfplan Artifacts
      # - name: Download Plan Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: tfplan
      #     path: ${{ env.CONFIG_DIRECTORY }}

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      # Step 4: Configure AWS credentials
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.CONFIG_DIRECTORY }}